server:
  port: 47075
spring:
  application:
    name: auth
eureka:
  instance:
    hostname: auth-service
  client:
    service-url:
      defaultZone: http://eurekaserver:47073/eureka
security:
  jwt:
    access: 36000000
    refresh: 2592000000
    secret: aGZiYmtiYWllYmNpZWFpZWJsZWNldWNlY2xhZWNhaWJlbGNhZWN3Q0VCV0VXSUM